template_name: dellos10.j2
ansible_become: false
ansible_network_os: sense.dellos10.dellos10
ansible_ssh_pass: MySuperDuperPassword
ansible_ssh_user: MySuperDuperUsername
hostname: dellos9_s0
# For snmp monitoring parameters, see Session API parameters: https://easysnmp.readthedocs.io/en/latest/session_api.html
snmp_monitoring:
  hostname: 1.2.3.4
  community: 'community'
  version: 2
